import { Cairo } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Provider from "./Provider";

const inter = Cairo({ weight : '300', subsets: ["arabic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Provider>
        {children}
        <Footer/>
        </Provider>
      </body>
    </html>
  );
}
